// AUTO-GENERATED by generate-manifest.js — do not edit by hand.
// Titles/icons below are preserved from previous manual curation where
// they existed; additions/removals come from docs/*.md frontmatter.
// Array body is valid JSON (double-quoted keys/strings) — see extractNavTree
// in script-docs.js, which JSON.parses this rather than evaluating it as JS.
CONFIG.NAV_TREE = [

  {
    "title": "Architecture",
    "icon": "fa-solid fa-folder",
    "children": [
      { "title": "Boot Process", "slug": "arch/boot" },
      { "title": "Btrfs Deep Dive", "slug": "arch/btrfs" },
      { "title": "Build Pipeline", "slug": "arch/build-pipeline" },
      { "title": "Dracut Initramfs Module", "slug": "arch/dracut-module" },
      { "title": "Filesystem Structure", "slug": "arch/filesystem" },
      { "title": "Overlay Filesystem", "slug": "arch/overlay" },
    ]
  },

  {
    "title": "Concepts",
    "icon": "fa-solid fa-folder",
    "children": [
      { "title": "Atomic Updates", "slug": "concepts/atomic-updates" },
      { "title": "Blue-Green Deployment", "slug": "concepts/blue-green" },
      { "title": "Immutability", "slug": "concepts/immutability" },
      { "title": "Persistence Strategy", "slug": "concepts/persistence" },
    ]
  },

  {
    "title": "Enterprise",
    "icon": "fa-solid fa-folder",
    "children": [
      { "title": "Cloud Images Beyond AWS", "slug": "enterprise/cloud-images" },
      { "title": "Compliance & Benchmarks", "slug": "enterprise/compliance" },
      { "title": "Fleet Monitoring Runbook", "slug": "enterprise/fleet-monitoring" },
      { "title": "OEM & Fleet Deployment", "slug": "enterprise/fleet" },
    ]
  },

  {
    "title": "Installation",
    "icon": "fa-solid fa-folder",
    "children": [
      { "title": "First Boot", "slug": "install/first-boot" },
      { "title": "Pre-Installation Setup", "slug": "install/pre-install" },
      { "title": "System Requirements", "slug": "install/requirements" },
      { "title": "Installation Steps", "slug": "install/steps" },
    ]
  },

  {
    "title": "Introduction",
    "icon": "fa-solid fa-folder",
    "children": [
      { "title": "How Shanios Compares", "slug": "intro/comparison" },
      { "title": "Getting Started", "slug": "intro/getting-started" },
      { "title": "Migrating from Traditional Linux", "slug": "intro/migrating" },
      { "title": "System Optimizations", "slug": "intro/optimizations" },
      { "title": "Switching from Windows & macOS", "slug": "intro/switching-from-windows" },
      { "title": "User Configuration", "slug": "intro/user-config" },
      { "title": "What is Shanios?", "slug": "intro/what-is-shanios" },
      { "title": "What's Included", "slug": "intro/whats-included" },
    ]
  },

  {
    "title": "Networking",
    "icon": "fa-solid fa-folder",
    "children": [
      { "title": "Apache HTTP Server", "slug": "networking/apache" },
      { "title": "apcupsd (UPS Daemon)", "slug": "networking/apcupsd" },
      { "title": "arpwatch (ARP Monitor)", "slug": "networking/arpwatch" },
      { "title": "Avahi (mDNS)", "slug": "networking/avahi" },
      { "title": "BIND (Authoritative DNS)", "slug": "networking/bind" },
      { "title": "Bluetooth", "slug": "networking/bluetooth" },
      { "title": "Caddy", "slug": "networking/caddy" },
      { "title": "Cloudflared Tunnels", "slug": "networking/cloudflared" },
      { "title": "dnscrypt-proxy (Encrypted DNS)", "slug": "networking/dnscrypt-proxy" },
      { "title": "dnsmasq (Local DNS)", "slug": "networking/dnsmasq" },
      { "title": "Exim (Mail Transfer Agent)", "slug": "networking/exim" },
      { "title": "Fail2ban (Brute-Force Protection)", "slug": "networking/fail2ban" },
      { "title": "Firewall (firewalld)", "slug": "networking/firewalld" },
      { "title": "gpsd (GPS Daemon)", "slug": "networking/gpsd" },
      { "title": "How Container Networking Works", "slug": "networking/how-container-networking-works" },
      { "title": "IP Addressing & Routing", "slug": "networking/ip-addressing" },
      { "title": "iptables and nftables Basics", "slug": "networking/iptables-and-nftables-basics" },
      { "title": "KDE Connect", "slug": "networking/kdeconnect" },
      { "title": "Kerberos", "slug": "networking/kerberos" },
      { "title": "ModemManager (Mobile Broadband)", "slug": "networking/modemmanager" },
      { "title": "nbd-server (Network Block Device)", "slug": "networking/nbd" },
      { "title": "Network Debugging Quick Reference", "slug": "networking/network-debugging-quick-reference" },
      { "title": "Network Tools", "slug": "networking/network-tools" },
      { "title": "NetworkManager & VPN", "slug": "networking/networkmanager-vpn" },
      { "title": "NFS File Sharing", "slug": "networking/nfs" },
      { "title": "openresolv (DNS)", "slug": "networking/openresolv" },
      { "title": "OpenSSH", "slug": "networking/openssh" },
      { "title": "PowerDNS", "slug": "networking/powerdns" },
      { "title": "Remote Desktop", "slug": "networking/remote-desktop" },
      { "title": "rsyncd (rsync Daemon)", "slug": "networking/rsyncd" },
      { "title": "Samba (SMB/CIFS)", "slug": "networking/samba" },
      { "title": "slapd (OpenLDAP)", "slug": "networking/slapd" },
      { "title": "snmpd (SNMP)", "slug": "networking/snmpd" },
      { "title": "SSHFS", "slug": "networking/sshfs" },
      { "title": "Tailscale VPN", "slug": "networking/tailscale" },
      { "title": "TCP/IP Fundamentals", "slug": "networking/tcp-ip-fundamentals" },
      { "title": "Troubleshooting", "slug": "networking/troubleshooting" },
      { "title": "Virtual Networking", "slug": "networking/virtual-networking" },
      { "title": "WireGuard Road Warrior — Split-Tunnel", "slug": "networking/wireguard-road-warrior" },
      { "title": "WireGuard (Manual)", "slug": "networking/wireguard" },
      { "title": "Wi-Fi & Wireless Firmware", "slug": "networking/wireless" },
    ]
  },

  {
    "title": "Security",
    "icon": "fa-solid fa-folder",
    "children": [
      { "title": "AppArmor (Mandatory Access Control)", "slug": "security/apparmor" },
      { "title": "Audit (auditd)", "slug": "security/audit" },
      { "title": "Security Features", "slug": "security/features" },
      { "title": "Firmware Updates (fwupd)", "slug": "security/fwupd" },
      { "title": "gen-efi Reference", "slug": "security/gen-efi" },
      { "title": "Directory Encryption (gocryptfs)", "slug": "security/gocryptfs" },
      { "title": "Hardware Authentication", "slug": "security/hardware-auth" },
      { "title": "Pacman Keyring & Trust Root", "slug": "security/keyring" },
      { "title": "LUKS Management", "slug": "security/luks" },
      { "title": "Lynis (Security Auditing)", "slug": "security/lynis" },
      { "title": "Permissions & Authorization", "slug": "security/permissions" },
      { "title": "rkhunter (Rootkit Hunter)", "slug": "security/rkhunter" },
      { "title": "Secure Boot", "slug": "security/secure-boot" },
      { "title": "TPM2 Enrollment", "slug": "security/tpm2" },
    ]
  },

  {
    "title": "Self-Hosting & Servers",
    "icon": "fa-solid fa-folder",
    "children": [
      { "title": "AI & LLMs", "slug": "servers/ai-llms" },
      { "title": "Backups & Storage", "slug": "servers/backups-sync" },
      { "title": "Business Intelligence & Analytics", "slug": "servers/business-intelligence" },
      { "title": "Clusters & High Availability", "slug": "servers/clusters" },
      { "title": "Communication", "slug": "servers/communication" },
      { "title": "Databases — MongoDB & FerretDB", "slug": "servers/databases/mongodb" },
      { "title": "Databases — Messaging, Analytics & Specialty Stores", "slug": "servers/databases/other" },
      { "title": "Databases — PostgreSQL & MariaDB", "slug": "servers/databases/postgresql" },
      { "title": "Databases — Redis & Compatible Alternatives", "slug": "servers/databases/redis" },
      { "title": "DevOps — Code Hosting & CI/CD", "slug": "servers/devops/ci-cd" },
      { "title": "DevOps — Infrastructure as Code, Containers & Utilities", "slug": "servers/devops/other" },
      { "title": "Dev Tools — Version Control, CI/CD & Registries", "slug": "servers/devtools" },
      { "title": "Education & E-Learning", "slug": "servers/education" },
      { "title": "Finance & Accounting", "slug": "servers/finance" },
      { "title": "Game Servers", "slug": "servers/game-servers" },
      { "title": "Home Automation", "slug": "servers/home-automation" },
      { "title": "IoT & Monitoring", "slug": "servers/iot" },
      { "title": "Kubernetes — GitOps & Continuous Delivery", "slug": "servers/kubernetes/gitops" },
      { "title": "Kubernetes — Networking & Ingress", "slug": "servers/kubernetes/networking" },
      { "title": "Kubernetes — Observability (Metrics, Dashboards & SLOs)", "slug": "servers/kubernetes/observability" },
      { "title": "Kubernetes — Cluster Operations & Platform Engineering", "slug": "servers/kubernetes/operations" },
      { "title": "Kubernetes Overview — Key Concepts & Distributions", "slug": "servers/kubernetes/overview" },
      { "title": "Kubernetes — Security & Policy", "slug": "servers/kubernetes/security" },
      { "title": "Kubernetes — Storage", "slug": "servers/kubernetes/storage" },
      { "title": "Kubernetes — Troubleshooting", "slug": "servers/kubernetes/troubleshooting" },
      { "title": "Kubernetes — Workload Patterns", "slug": "servers/kubernetes/workloads" },
      { "title": "Mail Servers", "slug": "servers/mail" },
      { "title": "Container Management & Lifecycle", "slug": "servers/management" },
      { "title": "Media & Entertainment", "slug": "servers/media" },
      { "title": "Medical & Health", "slug": "servers/medical" },
      { "title": "Monitoring — Grafana, Loki & Tracing", "slug": "servers/monitoring/grafana" },
      { "title": "Monitoring — Log Aggregation (ELK, OpenSearch & Vector)", "slug": "servers/monitoring/logs" },
      { "title": "Monitoring — Prometheus, Alerting & Long-Term Storage", "slug": "servers/monitoring/prometheus" },
      { "title": "Monitoring — Uptime, Lightweight Dashboards & All-in-One Platforms", "slug": "servers/monitoring/uptime" },
      { "title": "AdGuard Home", "slug": "servers/networking/adguard-home" },
      { "title": "Blocky", "slug": "servers/networking/blocky" },
      { "title": "ddns-updater (Dynamic DNS)", "slug": "servers/networking/ddns-updater-dynamic-dns" },
      { "title": "Firezone", "slug": "servers/networking/firezone" },
      { "title": "frp (Fast Reverse Proxy)", "slug": "servers/networking/frp-fast-reverse-proxy" },
      { "title": "FRRouting — BGP, OSPF & Dynamic Routing", "slug": "servers/networking/frrouting-bgp-ospf-dynamic-routing" },
      { "title": "Gluetun (VPN Client Container)", "slug": "servers/networking/gluetun-vpn-client-container" },
      { "title": "HAProxy", "slug": "servers/networking/haproxy" },
      { "title": "Headscale (Self-Hosted Tailscale Alternative)", "slug": "servers/networking/headscale" },
      { "title": "Hysteria 2 (High-Loss Networks)", "slug": "servers/networking/hysteria-2-high-loss-networks" },
      { "title": "Kea DHCP", "slug": "servers/networking/kea-dhcp" },
      { "title": "LibreNMS", "slug": "servers/networking/librenms" },
      { "title": "Nebula (Overlay Mesh Network)", "slug": "servers/networking/nebula-overlay-mesh-network" },
      { "title": "NetBird", "slug": "servers/networking/netbird" },
      { "title": "NetBox", "slug": "servers/networking/netbox" },
      { "title": "Nginx Proxy Manager", "slug": "servers/networking/nginx-proxy-manager" },
      { "title": "Ntopng", "slug": "servers/networking/ntopng" },
      { "title": "OpenVPN", "slug": "servers/networking/openvpn" },
      { "title": "Outline VPN", "slug": "servers/networking/outline-vpn" },
      { "title": "Pangolin", "slug": "servers/networking/pangolin" },
      { "title": "phpIPAM — IP Address Management", "slug": "servers/networking/phpipam" },
      { "title": "Pi-hole", "slug": "servers/networking/pi-hole" },
      { "title": "Pritunl", "slug": "servers/networking/pritunl" },
      { "title": "SearXNG", "slug": "servers/networking/searxng" },
      { "title": "Squid (Caching Proxy)", "slug": "servers/networking/squid-caching-proxy" },
      { "title": "Technitium DNS Server", "slug": "servers/networking/technitium" },
      { "title": "Traefik", "slug": "servers/networking/traefik" },
      { "title": "Unbound", "slug": "servers/networking/unbound" },
      { "title": "WireGuard / WG-Easy", "slug": "servers/networking/wireguard-easy" },
      { "title": "Xray / V2Ray — Protocol-Obfuscating Proxy", "slug": "servers/networking/xray-v2ray-protocol-obfuscating-proxy" },
      { "title": "ZeroTier (Self-Hosted Controller)", "slug": "servers/networking/zerotier-self-hosted-controller" },
      { "title": "OpenStack & Private Cloud", "slug": "servers/openstack" },
      { "title": "Productivity — File Sync (Nextcloud, Syncthing & More)", "slug": "servers/productivity/file-sync" },
      { "title": "Productivity — Wikis & Knowledge Bases", "slug": "servers/productivity/knowledge-base" },
      { "title": "Productivity — Notes, Bookmarks & RSS", "slug": "servers/productivity/notes-bookmarks" },
      { "title": "Productivity — Project Management & CRM", "slug": "servers/productivity/project-management" },
      { "title": "Productivity — Publishing & Design Tools", "slug": "servers/productivity/publishing-design" },
      { "title": "Productivity — Household & Personal Utilities", "slug": "servers/productivity/utilities" },
      { "title": "Security & Identity — SSO, Directory & Passwordless (Authelia, Authentik, Keycloak, Zitadel, LLDAP, Kanidm)", "slug": "servers/security/authelia" },
      { "title": "Security — CrowdSec, PKI, Secrets & SIEM", "slug": "servers/security/pki-secrets-siem" },
      { "title": "Security & Identity — Scanning, SBOM & Policy Enforcement", "slug": "servers/security/policies" },
    ]
  },

  {
    "title": "Software & Apps",
    "icon": "fa-solid fa-folder",
    "children": [
      { "title": "AI-Assisted Development", "slug": "software/ai-development" },
      { "title": "AppImage", "slug": "software/appimage" },
      { "title": "Apptainer (HPC Containers)", "slug": "software/apptainer" },
      { "title": "Bottles (Windows Compatibility)", "slug": "software/bottles" },
      { "title": "Containers", "slug": "software/containers" },
      { "title": "Development Environments", "slug": "software/development" },
      { "title": "Distrobox", "slug": "software/distrobox" },
      { "title": "Flatpak", "slug": "software/flatpak" },
      { "title": "Gaming", "slug": "software/gaming" },
      { "title": "GPU Acceleration & HPC Containers", "slug": "software/gpu-containers" },
      { "title": "Homebrew", "slug": "software/homebrew" },
      { "title": "LXC and LXD", "slug": "software/lxc-lxd" },
      { "title": "Nix Package Manager", "slug": "software/nix" },
      { "title": "Building & Adding Packages", "slug": "software/shani-pkgbuilds" },
      { "title": "Shani Package Repository", "slug": "software/shani-repo" },
      { "title": "Snaps", "slug": "software/snaps" },
      { "title": "systemd-nspawn", "slug": "software/systemd-nspawn" },
      { "title": "Virtual Machines", "slug": "software/vms" },
      { "title": "Android (Waydroid)", "slug": "software/waydroid" },
    ]
  },

  {
    "title": "System",
    "icon": "fa-solid fa-folder",
    "children": [
      { "title": "Accessibility", "slug": "system/accessibility" },
      { "title": "Audio (PipeWire)", "slug": "system/audio" },
      { "title": "Backup & Recovery", "slug": "system/backup" },
      { "title": "Command Cheatsheet", "slug": "system/cheatsheet" },
      { "title": "cronie (Cron Scheduler)", "slug": "system/cronie" },
      { "title": "GPU & Graphics Drivers", "slug": "system/gpu" },
      { "title": "Hardware", "slug": "system/hardware" },
      { "title": "Kernel Modules", "slug": "system/kernel-modules" },
      { "title": "Logging", "slug": "system/logging" },
      { "title": "File Permissions & Attributes", "slug": "system/permissions" },
      { "title": "Power Management", "slug": "system/power" },
      { "title": "Printing & Scanning", "slug": "system/printing" },
      { "title": "Process Management", "slug": "system/process-management" },
      { "title": "Storage", "slug": "system/storage" },
      { "title": "Systemd", "slug": "system/systemd" },
      { "title": "Users & Groups", "slug": "system/users-groups" },
    ]
  },

  {
    "title": "Updates & Config",
    "icon": "fa-solid fa-folder",
    "children": [
      { "title": "Release Channels", "slug": "updates/channels" },
      { "title": "System Config", "slug": "updates/config" },
      { "title": "shani-health Reference", "slug": "updates/shani-health" },
      { "title": "Factory Reset (shani-reset)", "slug": "updates/shani-reset" },
      { "title": "Shell & Environment", "slug": "updates/shell" },
      { "title": "System Updates", "slug": "updates/system" },
      { "title": "User Provisioning (shani-user-setup)", "slug": "updates/user-setup" },
    ]
  },

  {
    "title": "FAQ",
    "icon": "fa-solid fa-folder",
    "children": [
      { "title": "FAQ", "slug": "faq" },
    ]
  },

  {
    "title": "Overview",
    "icon": "fa-solid fa-folder",
    "children": [
      { "title": "Overview", "slug": "overview" },
    ]
  },

  {
    "title": "Troubleshooting",
    "icon": "fa-solid fa-folder",
    "children": [
      { "title": "Troubleshooting", "slug": "troubleshooting" },
    ]
  },
];
