name: Build docs manifest

on:
  push:
    branches: [main]
    paths:
      - 'docs/**.md'
      - 'config-docs.js'
      - 'generate-manifest.js'
      - '.github/workflows/build-manifest.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: shani8dev/shani-ci-commons/.github/workflows/build.yml@main
    with:
      build-type: manifest

  security:
    name: Security
    uses: shani8dev/shani-ci-commons/.github/workflows/security.yml@main
    with:
      scan-type: secrets
    needs: build
